server:
  port: 8080
spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://config-server:8888/
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: http://book-service:8081
          predicates:
            - Path=/books/**
management:
  endpoints:
    web:
      exposure:
        include: health,info