server:
  port: 9002
spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://config-server:8888/
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: password
management:
  endpoints:
    web:
      exposure:
        include: health,info