server:
  port: 9003
spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://config-server:8888/
  data:
    mongodb:
      uri: mongodb://localhost:27017/userdb
management:
  endpoints:
    web:
      exposure:
        include: health,info